#.github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/frontend'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pip'
    directories:
      - '/backend'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directories:
      - '/.github/workflows'
    schedule:
      interval: 'weekly'